# Generated by Django 2.1.7 on 2019-03-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('js_count', models.IntegerField(max_length=100)),
                ('css_count', models.IntegerField(max_length=100)),
                ('html_count', models.IntegerField(max_length=100)),
            ],
        ),
    ]
