# Generated by Django 2.1.7 on 2019-03-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190306_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='img_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
